DROP TABLE ANIMALS;
CREATE TABLE ANIMALS
(
  CHIPREGISTRATIONNUMBER VARCHAR2(5) NOT NULL 
, DATEOFBIRTH DATE 
, NAME VARCHAR2(128) 
, RESERVED NUMBER(1) DEFAULT 0 NOT NULL
, PRICE NUMBER(6,2) NOT NULL
, LASTWALKDATE DATE
, BADHABITS VARCHAR2(255) 
, CONSTRAINT ANIMALS_PK PRIMARY KEY 
  (
    CHIPREGISTRATIONNUMBER 
  )
  ENABLE 
);